In [1]:
import pandas as pd
import seaborn as sns
%matplotlib inline

In [25]:
df = pd.read_csv('CARIT_allRaw.csv')
df.head()
df.shape

(118404, 31)

In [6]:
df.columns

Index(['condFile', 'trialNum', 'stim', 'corrAns', 'prepotency', 'ISI',
       'shapeStartTime', 'shapeEndTime', 'fixStartTime', 'fixEndTime',
       'nogoCondition', 'resp', 'trialResp.firstKey', 'trialResp.firstRt',
       'corrRespMsg', 'corrRespCode', 'corrRespTrialType', 'isiPress.keys',
       'isiPress.rt', 'hitCount', 'missCount', 'falseAlarmCount',
       'corrRejectCount', 'totalAcc', 'goAcc', 'nogoAcc', 'goFiveBackAvg',
       'nogoFiveBackAvg', 'totalFiveBackAvg', 'filename', 'sessionID'],
      dtype='object')

In [28]:
cols = ['sessionID', 'filename', 'condfile', 'trialNum', 'stim', 'corrAns', 'shapeStartTime', 'shapeEndTime', 'fixStartTime', 'fixEndTime', 'trialResp.firstRt']
df.loc[df['trialResp.firstRt'] < df['shapeStartTime'], cols]  # .iloc[1]['filename']
(df['trialResp.firstRt'] - df['shapeStartTime'] < .2).sum()

263

In [15]:
!open -a "Microsoft Excel" /Users/kastman/Dropbox/ANDL/ProjectAnalyses/HCPD/Behavioral/data/CARIT_HCD0039128_V1_A_run1_wide.csv

In [16]:
df1 = pd.read_csv("/Users/kastman/Dropbox/ANDL/ProjectAnalyses/HCPD/Behavioral/data/CARIT_HCD0039128_V1_A_run1_wide.csv")

In [18]:
df1[['shapeStartTime', 'trialResp.firstRt']]

    shapeStartTime  trialResp.firstRt
0              NaN                NaN
1              NaN                NaN
2              NaN                NaN
3              NaN                NaN
4         8.044029           8.593850
5        10.142855          10.659818
6        15.241740          15.825678
7        17.341643                NaN
8        18.941636          19.410261
9        21.041168          21.575773
10       23.141068          23.558992
11       24.741243          25.225387
12       26.840669          27.342337
13       29.940544          30.425987
14       33.040162                NaN
15       34.640718          35.125021
16       37.739725          38.241822
17       39.840360                NaN
18       42.939298          43.374254
19       44.539231          45.040680
20       46.639077                NaN
21       48.238800          48.773222
22       53.337801          53.823186
23       56.438124          56.887686
24       59.538585                NaN
25       61.637050          62.089754
26       63.737555          64.222972
27       65.337348          65.938569
28       66.937336                NaN
29       70.036923          70.488083
..             ...                ...
66      161.232650         161.767100
67      163.332453         163.850554
68      165.432917                NaN
69      167.032120         167.557624
70      169.131049         169.683502
71      174.231488         174.682170
72      176.331281         176.849465
73      178.431817                NaN
74      180.031273         180.616361
75      183.130199         183.565979
76      185.231302                NaN
77      187.330475         187.765481
78      188.929677         189.365273
79      192.029873         192.548044
80      193.629891                NaN
81      195.730357         196.214183
82      197.829562         198.445059
83      199.429492         199.963151
84      202.529731                NaN
85      204.628941         205.164165
86      206.228133         206.796401
87      208.328710         208.946837
88      211.428229         212.013333
89      213.028417         213.496535
90      215.128857         215.580654
91      217.227911         217.662781
92      218.827706                NaN
93      220.427619         220.945262
94      223.527279         224.045591
95      226.627234         227.009017

[96 rows x 2 columns]

In [21]:
!open -a "Microsoft Excel" /Users/kastman/Dropbox/ANDL/ProjectAnalyses/HCPD/Behavioral/data/CARIT_HCD1268350_V1_A_run2_wide.csv